// Generated by CoffeeScript 1.10.0
(function() {
  var groceryList, total;

  groceryList = [
    {
      name: "milk",
      price: 2.79
    }, {
      name: "bread",
      price: 3.49
    }, {
      name: "bananas",
      price: 3.49
    }, {
      name: "chicken breasts",
      price: 11.42
    }, {
      name: "yogurt",
      price: 5.69
    }
  ];

  total = 0;

  groceryList.forEach(function(item) {
    console.log(item.name + ": $" + item.price);
    return total += item.price;
  });

  console.log("TOTAL: $" + (total.toFixed(2)));

}).call(this);
